### ISSUE TITLE
New Relic Deployments don't work unless a --tag is given

### ISSUE THREAD

**Issue by blytheaw** [fabfuel/ecs-deploy#143]
Hello!

I would love to use the built in New Relic deployment recorder, but it looks like it requires the use of the `--tag` option. I'm using multi-container tasks so I am using `-i` to replace images explicitly rather than use the same tag for all images.

It would be nice to be able to use the deployment recorder in this case. In this case, an arbitrary revision would have to be provided to use as the version rather than deriving it from a tag passed in, since there could be multiple images with different tags provided. 

Perhaps a `--newrelic-revision` argument could be added to allow for a user-specified revision? This value could default to either the `--tag` if provided, or the first tag provided by an `--image` option.

**Comment by fabfuel** [comment]
Hi @blytheaw,

sounds like a very useful addition!

It agree, to default to the tag (as of today) but giving the option to overwrite it explicitly with a new parameter. 

But i would rather not implicitly fall back to the first image, because if you have multiple containers in your task definition, but only track one deployment in New Relic, it's unclear which image/revision/tag of the multiple containers should be used as the one application version tracked in New Relic.

Would you be able to contribute this in a PR?

Thanks a lot - all the best
Fabian

**Comment by blytheaw** [comment]
@fabfuel Sure, I'll give that a shot. Thanks!

**Comment by blytheaw** [comment]
Fixed by https://github.com/fabfuel/ecs-deploy/pull/148
