### ISSUE TITLE
Ability to set the ECS Service tasks desired count to '0'

### ISSUE THREAD

**Issue by kdonekal** [fabfuel/ecs-deploy#156]
Hi @fabfuel ,

Can I set the ECS Deploy Service tasks desired count to 0 and bring it back to 1 or 2 after the deployment ?

I see the scale up and scale down command, so wanted to confirm the count that command illustrates in the readme example is that a desired count or scale up or down count.

**Comment by fabfuel** [comment]
Hi @kdonekal,

yes, you can. The `scale` command changes the desired count of the service. Theoretically you can change it to `0` before the deployment and scale back up afterwards, but one of the major advantages of deploying with ECS is, that it takes care for the rolling update/deployment so that you can achieve a deployment without downtime.

If you scale down to `0` your service will be unavailable.

Best
Fabian
