### ISSUE TITLE
ECS Dedeploy Timeout 

### ISSUE THREAD

**Issue by angelozignaltinho** [fabfuel/ecs-deploy#209]
Any updates on this? Does ecs deploy support blue green? I have the new container running along side the old version as well. ecs-deploys timeouts. However the container is running succesfully. After a little longer the old container dies and the new one is still running. But I get the following error
`Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout` Only once i increase the timeout to 600 seconds. The deployment is successful at 426 seconds. is there a way I can change this to a lower number by overriding some defaults?

**Comment by fabfuel** [comment]
Hay, I'm closing this as duplicate, please follow up in #120 regarding Blue/Green Deployments.

Regarding your timeout: Did you see the link/linked page you quoted?

The time it takes to deploy is only depending on your containers. To speed it up, you have to optimize the startup time of your application(s), you can not increase the deployment time with ecs-deploy. You only tell ecs-deploy how long to wait for a typical deployment, otherwise ecs-deploy will fail with timeout, as you described. Please just use a longer timeout until you optimized the startup time of your app(s).

Best
Fabian

**Comment by angelozignaltinho** [comment]
How does ecs-deploy check if the container has successfully started? I can see in the console that the container has started but ecs-deploy is still waiting.

**Comment by fabfuel** [comment]
@angelozignaltinho please stop posting your same answers and questions in multiple issues, instead please show some appreciation for other people trying to help you out here for free.

A deployment is only finished, if all old containers have stopped. And they only stop, if the desired count of new containers is running successfully. Please check the `Deployments` tab in your ECS service. As long as you see more than one deployment there, ecs-deploy is waiting for the active deployment to succeed or fail.
