### ISSUE TITLE
Deployment time with blue-green methodology

### ISSUE THREAD

**Issue by arminorlik** [fabfuel/ecs-deploy#52]
Hi, 
I have big problem with deployment by use ecs-deploy. Of course it works very well, but I encountered situation when I want to deploy my image according to blue-green methodology with 3 active instance in one cluster and managed by one service with desired 2 numbers of the same task. So it's obvious that when I start ecs-deploy it deploy my updated task into empty instance, and next show my warning about not enough space and resources for next deploy: "service was unable to place a task because no container instance met all of its requirements." And AWS throw me this info two times with two time intervals (approximately 8 minutes). I Assume that meanwhile he is trying to deploy and that's true he can find any free instance BUT according to blue-green methodology, after first deploy he should drain next instance and done next deploy. Of course finnaly after two tries and warnings he do it what i want but my pipeline is much longer and in my opinion it's just a waste of time. Maybe there is any option to force ecs to deploy without any info and warning (--ignore-warnings in this particular situation doesn't work)?

**Comment by fabfuel** [comment]
Hi @arminorlik,

this issue is not related to ecs-deploy, i think it's about configuring ECS in general.

As I understand, your containers have at least one constraint (e.g. a fixed port), which causes that only one container can be executed on a single instance at a time, right?

This problem can be solved by setting appropriate values in the deployment configuration in the service. What are the current values for "Minimum healthy percent" and "Maximum percent"?

If you have 3 instances and a desired count of 2, the "Maximum percent" has to be 150, which means there will never be more than 3 containers (150% of 2) running at the same time. 
The "Minimum healthy percent" can be 100% or less. If you chose 50%, the deployment will probably be faster.

This is what should happen with this config and a desired count of 2:
- ECS starts one new container => 150% of 2
- ECS stops one old container => 100% of 2
- ECS starts the second new container => 150% of 2
- ECS stops the second old container => 100% of 2
- done.

If "Maximum percent" is e.g. 200%, ECS first tries to spin up 2 new containers, which fails, because there are only 3 instances in the cluster. Then you receive the error mentioned above.

I hope that was helpful.

Best
Fabian

**Comment by arminorlik** [comment]
Hi @fabfuel 
thank you for answer. My current service settings looks like this:
Number of tasks 2
Minimum healthy percent 100
Maximum percent 300
And I totally agree with your advice how this service should scale up upon depends on current deploy needs. And I thought that with this settings and three instances it, during deploy new image it should deploy step by step us below:
1. first deploy to one free instance,
2. second deploy to auto prepared on this situation (no free instances) new instance,
3. draining and deleting redundant instances to achieve desired number of running task - 2
But unfortunately he despite of this settings instead of this steps, services tries to process only on three instances (which are prepared by me) - and it doesn't look for any scale up actions. Maybe you have any  speculation why how ecs is so stubborn;)?

**Comment by fabfuel** [comment]
What do you mean with "scale up actions"? Start more instances? You can do that, autoscaling can be triggered by ECS, but this needs to be configured as well.

As mentioned above, the "Maximum percent" of 300 is the problem. If you change it to 150, it should just work as you want.
I would not

**Comment by arminorlik** [comment]
Yeaaaasss! It woooooorrrrkssssss:) Thank you very much! When you'll be in Poland just give me a sign, I'll buy you the best beer:)
