### ISSUE TITLE
Old task definition is marked as inactive 

### ISSUE THREAD

**Issue by smuryginim** [fabfuel/ecs-deploy#92]
Hello! Thanks for the great tool!
We currently use it with the option:

> Deploy a new version of your service:
> $ ecs deploy my-cluster my-service --tag 1.2.3 --timeout -1

It works fine, but the previous task definition is marked as INACTIVE with such option.
Is it possible to have an option to leave the previous task definition in ACTIVE status for rollback use cases?

**Comment by nurikabe** [comment]
Just ran afoul of this. What's odd is that setting `--timeout -1` always immediately deregisters the current task, however using a normal timeout and letting the process run to completion does not remove the current active task (even though output would indicate otherwise).

Something to do with Fargate-based deployment perhaps?

**Comment by fabfuel** [comment]
Hi @smuryginim & @nurikabe, 

the old task definition is deregistered at the end of the process. When running the tool with `--timeout -1` there is just no waiting time, which means the "end of the process" and therefore the deregistration happens immediately.

There already is a flag for **not deregistering** the current task definition, called `--no-deregister`. Please see the help via `ecs deploy --help`
```
--deregister / --no-deregister  Deregister or keep the old task definition
                                (default: --deregister)
```

I hope that helps!
And thanks for using the tool 😎 

Best
Fabian
